# This docker-compose file is only for local development

version: '3.2'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./api
        target: /srv
      - type: volume
        source: api_node_modules
        target: /srv/node_modules
    ports:
      - '4000:4000'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_GRAPHQL_URI: http://localhost:4000/
    depends_on:
      - api
    volumes:
      - type: bind
        source: ./client
        target: /srv
      - type: volume
        source: client_node_modules
        target: /srv/node_modules
    ports:
      - '3000:3000'

volumes:
  api_node_modules:
  client_node_modules:
